#!/usr/bin/env perl
use 5.12.0;
use Digest::MD5 qw(md5_hex);
use File::Path qw(make_path);
use Getopt::Long::Descriptive;

my ($opt, $usage) = describe_options(
  '%c %o [filecount]',
  [ 'target=s', 'name in which to build', { default => 'corpus' } ],
  [ 'depth=i',  'how many dirs deep are files? default: 3', { default => 3 } ],
);

warn "corpus already exists\n" if -d $opt->target;
make_path($opt->target);

my $max = $ARGV[0] || $usage->die;

my %files;
for (1 .. $max) {
  say;
  my $fn = md5_hex($_);
  my @dir;
  push @dir, substr $fn, 0, 2, '' until @dir == $opt->depth;
  my $target = join q{/}, $opt->target, @dir;
  make_path($target);
  open my $fh, '>', "$target/$fn" or die "can't open it: $!";
}

