#!/usr/bin/env perl
use 5.12.0;
use Digest::MD5 qw(md5_hex);
use File::Path qw(make_path);

warn "corpus already exists\n" if -d 'corpus';
make_path('corpus');

my $max = $ARGV[0] || die "usage: build-corpus <FILECOUNT>\n";

my %files;
for (1 .. $max) {
  say;
  my $fn = md5_hex($_);
  my ($a, $b, $c, $leaf) = $fn =~ /\A(..)(..)(..)(.+)\z/;
  make_path("corpus/$a/$b/$c");
  open my $fh, '>', "corpus/$a/$b/$c/$leaf" or die "can't open it: $!";
}

